# Generated by Django 4.1.7 on 2023-04-15 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_mbolemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MboleModel',
            new_name='MobileModel',
        ),
    ]
